### ISSUE TITLE
Systemjs error

### ISSUE THREAD

**Issue by Mewel** [pleerock/ng2-radio-group#1]
I get an error when using this directive:

SyntaxError: Unexpected token <
	Evaluating http://localhost:3000/ng2-radio-group/ng2-radio-group
	Error loading http://localhost:3000/dist/main.js
    at eval (native)
    at SystemJSLoader.__exec (http://localhost:3000/node_modules/systemjs/dist/system.src.js:1395:16)

Don't get any closer to the problem. This happens when I add the directive to the component:

@Component({
    selector: '...',
    changeDetection: ChangeDetectionStrategy.OnPush,
    templateUrl: '...',
    directives: [RADIO_GROUP_DIRECTIVES]
})

those are my dependencies

  "dependencies": {
    "angular2": "2.0.0-beta.8",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "ng2-radio-group": "0.0.2",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "systemjs": "0.19.22",
    "zone.js": "0.5.15"
  },

**Comment by pleerock** [comment]
I personally use it with system.js and have no problem with it. Maybe error in your system.js configuration? Try to post complete code what you are doing

**Comment by tobiloeb** [comment]
I have the same problem. 
angular2-polyfills.js:332 Error: SyntaxError: Unexpected token <
	Evaluating http://localhost:3000/ng2-radio-group/ng2-radio-group
	Error loading http://localhost:3000/app/main.js

My dependencies are:
"angular2": "2.0.0-beta.12",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.35.0",
    "ng2-radio-group": "0.0.2",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "systemjs": "0.19.24",
    "zone.js": "0.6.6"

**Comment by feliu** [comment]
+1

**Comment by janknobloch** [comment]
+1

**Comment by pleerock** [comment]
there should not be problem with installation of this component, but if anyone still have this issue please reopen this issue.
