### ISSUE TITLE
require?

### ISSUE THREAD

**Issue by jkufrin** [pleerock/ng2-radio-group#2]
Great plugin! Well documented.

How do you make it required though? I tried adding 'required' to both the input and the group. Neither work

**Comment by pleerock** [comment]
Thank you. Right now it seems to be impossible. I will fix it and make a new release on the next week.

**Comment by pleerock** [comment]
finally re-implemented. please update your version and take a look at [release notes](https://github.com/pleerock/ng2-radio-group#release-notes)
