### ISSUE TITLE
Can't import ng2-radio-group on angular 2 rc3

### ISSUE THREAD

**Issue by LeResKP** [pleerock/ng2-radio-group#3]
Hello,

There is an error when importing RADIO_GROUP_DIRECTIVES on angular 2 rc3 (The code works perfectly on rc1)

When doing:
import { RADIO_GROUP_DIRECTIVES } from "ng2-radio-group";

there is the following error:
EXCEPTION: Error: Uncaught (in promise): No Directive annotation found on CheckboxGroup

Do you have an idea where it comes from ?

Thks,
Aurélien

**Comment by pleerock** [comment]
just updated to rc.3 and everything seems working. what version of ng2-radio-group are you using?

**Comment by LeResKP** [comment]
I was using 0.0.4,  I just updated to 0.0.5 and got the same issue.

**Comment by LeResKP** [comment]
You are right, I create a small project and it works fine even with webpack. Will investigate. Thks!

**Comment by pleerock** [comment]
thanks for update 👍
